
service: serverless

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '2'

provider:
  name: azure
  region: UK South
  runtime: python3.8 # python3.7 or python3.8 also available
  os: linux  # linux is the only operating system available for python
  prefix: "scholarly"  # prefix of generated resource name
  subscriptionId: e7cbfebb-f482-46c4-a90b-126855b03325
  stage: prod
  # type: premium  # premium azure functions

  environment: # these will be created as application settings
    CONNECTION_STRING : ${file(credentials.json):CONNECTION_STRING}
    CONTAINER_NAME : ${file(credentials.json):CONTAINER_NAME}
    AUTHOR_IDS : ${file(credentials.json):AUTHOR_IDS}

  
plugins:
  - serverless-azure-functions
  - serverless-python-requirements
package:
  patterns:
    - '!env/**'
    - '!.env/**'
    - '!local.settings.json'
    - '!.vscode/**'
    - '!__pycache__/**'
    - '!node_modules/**'
    - '!.python_packages/**'
    - '!.funcignore'
    - '!package.json'
    - '!package-lock.json'
    - '!.gitignore'
    - '!.git/**'
  # - '!exclude-me.py'
  # - '!exclude-me-dir/**'
  #   - include-me.py
  #   - include-me-dir/**

functions:
          
  timer:
    handler: src/handlers/publications.main
    events:
      - timer: true
        # NCRONTAB format
        schedule: '0 0 3 * * *'
        # for testing (every 2 mins)
        #schedule: '0 */2 * * * *'
       
        

  