# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: serverless

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '2'

provider:
  name: azure
  region: UK South
  runtime: python3.8 # python3.7 or python3.8 also available
  os: linux  # linux is the only operating system available for python
  prefix: "scholarly"  # prefix of generated resource name
  subscriptionId: e7cbfebb-f482-46c4-a90b-126855b03325
  stage: prod
  # type: premium  # premium azure functions

  environment: # these will be created as application settings
    CONNECTION_STRING : ${file(credentials.json):CONNECTION_STRING}
    CONTAINER_NAME : ${file(credentials.json):CONTAINER_NAME}

  # you can define apim configuration here
  # apim:
  #   apis:
  #     - name: v1
  #       subscriptionRequired: false # if true must provide an api key
  #       displayName: v1
  #       description: V1 sample app APIs
  #       protocols:
  #         - https
  #       path: v1
  #       tags:
  #         - tag1
  #         - tag2
  #       authorization: none
  #   cors:
  #     allowCredentials: false
  #     allowedOrigins:
  #       - "*"
  #     allowedMethods:
  #       - GET
  #       - POST
  #       - PUT
  #       - DELETE
  #       - PATCH
  #     allowedHeaders:
  #       - "*"
  #     exposeHeaders:
  #       - "*"

plugins:
  - serverless-azure-functions
  - serverless-python-requirements
package:
  patterns:
    - '!env/**'
    - '!.env/**'
    - '!local.settings.json'
    - '!.vscode/**'
    - '!__pycache__/**'
    - '!node_modules/**'
    - '!.python_packages/**'
    - '!.funcignore'
    - '!package.json'
    - '!package-lock.json'
    - '!.gitignore'
    - '!.git/**'
  # - '!exclude-me.py'
  # - '!exclude-me-dir/**'
  #   - include-me.py
  #   - include-me-dir/**

functions:
  

  #publications:
    #handler: src/handlers/publications.main
    #events:
      #- http: true
       # methods:
        #  - GET
        #authLevel: anonymous
           
  timer:
    handler: src/handlers/publications.main
    events:
      - timer: true
        # 3am
        schedule: '0 3 * * * *'
        

  # The following are a few examples of other events you can configure:
  # storageBlob:
  #   handler: src/handlers/storageBlob
  #   events:
  #     - blob:
  #       x-azure-settings:
  #         name: blob # Specifies which name is available on `context`
  #         path: blob-sample/{blobName}
  #         connection: AzureWebJobsStorage # App Setting/environment variable which contains Storage Account Connection String
  # storageQueue:
  #   handler: src/handlers/storageQueue
  #   events:
  #     - queue: queue-sample
  #       x-azure-settings:
  #         name: message # Specifies which name is available on `context`
  #         connection: AzureWebJobsStorage
  # timer:
  #   handler: src/handlers/timer
  #   events:
  #     - timer:
  #       x-azure-settings:
  #         schedule: '*/10 * * * * *'
  